environment:
  matrix:
    - nodejs_version: "6.9.2"
      ADDON_VERSION: "48"

platform:
  - x64

install:
  - echo %ADDON_VERSION%
  - ps: Update-NodeJsInstallation $env:nodejs_version $env:platform
  - node -v
  - npm install -g npm
  - npm install -g nw-gyp node-pre-gyp
  - npm install

build: off

after_test:
  - powershell .\\ci\\appveyor\\inno_setup.ps1
  - rd /s /q %APPDATA%\..\Local\NuGet\Cache
  - set PATH="C:\Program Files (x86)\Inno Setup 5";%PATH%
  - set SRC=%cd%
  - echo %SRC%
  - copy misc\MSVSVersion.py %APPDATA%\npm\node_modules\nw-gyp\gyp\pylib\gyp\MSVSVersion.py
  - set NW_VERSION=0.17.6
  - set NW_RELEASE=v0.17.6
  - echo %NW_RELEASE%
  - cd node_modules/wotb
  - npm install --build-from-source
  - node-pre-gyp --runtime=node-webkit --target=%NW_VERSION% --msvs_version=2015 configure
  - node-pre-gyp --runtime=node-webkit --target=%NW_VERSION% --msvs_version=2015 build
  - copy %cd%\lib\binding\Release\node-webkit-%NW_RELEASE%-win32-x64\wotb.node %cd%\lib\binding\Release\node-v%ADDON_VERSION%-win32-x64\wotb.node /Y
  - cd ../naclb
  - npm install --build-from-source
  - node-pre-gyp --runtime=node-webkit --target=%NW_VERSION% --msvs_version=2015 configure
  - node-pre-gyp --runtime=node-webkit --target=%NW_VERSION% --msvs_version=2015 build
  - copy %cd%\lib\binding\Release\node-webkit-%NW_RELEASE%-win32-x64\naclb.node %cd%\lib\binding\Release\node-v%ADDON_VERSION%-win32-x64\naclb.node /Y
  - cd ../scryptb
  - npm install --build-from-source
  - node-pre-gyp --runtime=node-webkit --target=%NW_VERSION% --msvs_version=2015 configure
  - node-pre-gyp --runtime=node-webkit --target=%NW_VERSION% --msvs_version=2015 build
  - copy %cd%\lib\binding\Release\node-webkit-%NW_RELEASE%-win32-x64\scryptb.node %cd%\lib\binding\Release\node-v%ADDON_VERSION%-win32-x64\scryptb.node /Y
  - cd ../sqlite3
  - npm install --build-from-source
  - node-pre-gyp --runtime=node-webkit --target=%NW_VERSION% --msvs_version=2015 configure
  - node-pre-gyp --runtime=node-webkit --target=%NW_VERSION% --msvs_version=2015 build
  - copy %cd%\lib\binding\node-webkit-%NW_RELEASE%-win32-x64\node_sqlite3.node %cd%\lib\binding\node-v%ADDON_VERSION%-win32-x64\node_sqlite3.node /Y
  - cd ../..
  - npm prune --production
  - npm install duniter-ui --save --production
  - rd /s /q %cd%\node_modules\duniter-ui\node_modules
  - cd ..
  - mkdir duniter_release
  - set NW=nwjs-%NW_RELEASE%-win-x64
  - echo %NW%
  - set NW_GZ=%NW%.zip
  - echo %NW_GZ%
  - appveyor DownloadFile https://dl.nwjs.io/%NW_RELEASE%/nwjs-%NW_RELEASE%-win-x64.zip %NW_GZ%
  - 7z x %NW_GZ% 1> null
  - move %NW% %cd%\duniter_release\nw
  - mkdir %cd%\duniter_release\sources
  - xcopy %SRC%\gui\* %cd%\duniter_release\nw\ /s /e
  - xcopy %SRC%\* %cd%\duniter_release\sources\ /s /e
  - iscc %cd%\duniter_release\sources\duniter.iss /DROOT_PATH=%cd%\duniter_release
  - move %cd%\duniter_release\Duniter.exe %cd%\duniter\duniter-desktop-%APPVEYOR_REPO_TAG_NAME%-windows-x64.exe

artifacts:
  - path: duniter*.exe
    name: Duniter

deploy:
  release: v0.91.3
  provider: GitHub
  auth_token:
    secure: Vp/M0r0i1yhGR2nhrPWEbTiDIF6r0cmwbNDFZUzdFe5clWxPXtuC0lgIpOQI78zt
  artifact: /Duniter/
#  prerelease: true
  on:
    appveyor_repo_tag: true
